name: Sync CAPI and CAPV main to fork
on: 
  schedule: 
    # Daily at 4:20 UTC
    - cron: '20 4 * * *'
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo sync --branch main chrischdi/cluster-api --source kubernetes-sigs/cluster-api
        env:
          GH_TOKEN: ${{ secrets.SYNC_ACCESS_TOKEN }}
      - run: gh repo sync --branch main chrischdi/cluster-api-provider-vsphere --source kubernetes-sigs/cluster-api-provider-vsphere
        env:
          GH_TOKEN: ${{ secrets.SYNC_ACCESS_TOKEN }}
